### PR TITLE
QoL and necessities to Quanta

### PR DESCRIPTION
**Pull request by bioastroiner**
QoL recipes
tanks and some QoL mods including a grave and a fluid container mod
miscellaneous stuff to make pack more fun (COFH vanilla+ tools and satchel)

### CODE REVIEW

**Comment by bioastroiner** [comment]
image
satchel mod adds these backpacks which the last one is a great replacement for Dank/nulls and great for mining, i try balance the recipes ofc

**Comment by bioastroiner** [comment]
i gonna add satchels tommorow will balance the recipes so it fits the feel of the pack

**Comment by bioastroiner** [comment]
image
done!

**Comment by bioastroiner** [comment]
now i am done

**Comment by bioastroiner** [comment]
#24 fixed

**Comment by bioastroiner** [comment]
@joendter @Lach01298  this PR is done feel free to review/merge it

**Comment by joendter** [comment]
looks good to me, idk if i like the wood conversion thingy but ig it doesn't hurt...
the backpack recipes maybe need tweaking since i *think* there shouldn't be any difference between the plastic plated but since i'm too lazy to implement this i can't expect you to do this
overall nice QoL changes if you can confirm that it runs i will merge it

**Comment by bioastroiner** [comment]
> looks good to me, idk if i like the wood conversion thingy but ig it doesn't hurt... the backpack recipes maybe need tweaking since i _think_ there shouldn't be any difference between the plastic plated but since i'm too lazy to implement this i can't expect you to do this overall nice QoL changes if you can confirm that it runs i will merge it

bioplastics are basically gated behind manufacory which needs circuits and titanium but plastic is much early game just gated behind LCR , I don't how else would i improve the Backpack recipes since there is not much option to choose so feel free to suggest or change it as you fit. yea i tested it should work fine i tried to double test with the latest commit again but my ram is 90% full so... xD

**Comment by joendter** [comment]
image
this is kinda broken lol

**Pull request merged**
